### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [netvl/sshc#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by netvl** [comment]
Hi @timofonic,

Unfortunately, there are few problems with your suggestion.

First, I'm not really sure how the overall experience should be when sshc is used through a GUI. sshc basically constructs and executes an `ssh` command, which itself is purely terminal-based. It can only be used without a terminal for limited use-cases like creating non-interactive tunnels, but it would require a completely different approach for its GUI design. When you have a textual-only UI, it is simpler because the terminal you're running it in is reused.

Second, libyui appears to be written in C++. sshc, however, is written in Rust :) Quick search on crates.io showed that there are no bindings for libyui in Rust, and since it is C++, I don't think it would be easy to create one. I'm afraid I wouldn't be able to use it even if I wanted to and even if the above problem wouldn't exist.

But thanks for the suggestion anyway!
